In [1]:
#Creaing Arrays

In [1]:
import numpy as np

In [5]:
lst = list(np.arange(100,1000,5,dtype='int'))
lst

[100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 850,
 855,
 860,
 865,
 870,
 875,
 880,
 885,
 890,
 895,
 900,
 905,
 910,
 915,
 920,
 925,
 930

In [7]:
mat = np.arange(0,9).reshape(3,3)

In [8]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [1]:
import math

In [3]:
math.factorial(5)

120

In [4]:
math.sqrt(625)

25.0

In [5]:
math.lcm(5,50,100)

100

In [6]:
math.gcd(5,50,100)

5

In [9]:
math.pow(5,4)

625.0

In [2]:
import numpy as np

In [11]:
lst = [10,20,30,40,50]
arr1 =np.array(lst)
arr1

array([10, 20, 30, 40, 50])

In [13]:
print(type(arr1))

<class 'numpy.ndarray'>


In [14]:
tup1 =(10,20,30)
arr2 = np.array(tup1)
arr2

array([10, 20, 30])

In [15]:
list2d =[[10,20],[30,50],[50,55]]
arr2d =np.array(list2d)
arr2d

array([[10, 20],
       [30, 50],
       [50, 55]])

In [18]:
arr1.shape

(5,)

In [19]:
arr2d.shape

(3, 2)

In [32]:
print(type(arr1),'1d array type Same for below 2D also')
print(type(arr2d))
print(lst,'-------------------------1D Data')
print(list2d, '-------------------- 2D Dimension data')
print(arr1.shape,'<---------------------------------  1d Array shape')
print(arr2d.shape,'<--------------------------------  2d Array shape')

<class 'numpy.ndarray'> 1d array type Same for below 2D also
<class 'numpy.ndarray'>
[10, 20, 30, 40, 50] -------------------------1D Data
[[10, 20], [30, 50], [50, 55]] -------------------- 2D Dimension data
(5,) <---------------------------------  1d Array
(3, 2) <--------------------------------  2d Array



# Common ways to initialise the arrays using built in functions

#np.ones --> create arays of 1s

#create array of random numbers


In [35]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [46]:
np.arange(2,21,2,dtype='float')

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [40]:
arrC = np.arange(3,50,3)

In [41]:
list(arrC)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

In [43]:
lin1=np.linspace(0,50,9)
lin1

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [44]:
list(lin1)

[0.0, 6.25, 12.5, 18.75, 25.0, 31.25, 37.5, 43.75, 50.0]

In [45]:
50/9

5.555555555555555

In [47]:
lin2=np.linspace(0,50,9,dtype='int')
lin2

array([ 0,  6, 12, 18, 25, 31, 37, 43, 50])

In [60]:
# NP>ZEORS


np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [63]:
#ONES


np.ones((6,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

## 2d aray is callled ----------------> MATRIX

In [64]:
#IDENTITY MATRIX

# it is 5,5 Matrix in below case

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
## DIAGNNAL

np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [3]:
# RANDOm RANDOM

np.random.random(5)

array([0.59227408, 0.68994584, 0.69606936, 0.2550545 , 0.39978008])

In [79]:
x = np.random.random((5,5))
x


array([[0.56637833, 0.39185349, 0.96745906, 0.13400039, 0.74812167],
       [0.25819887, 0.42256834, 0.91520941, 0.30813169, 0.53872387],
       [0.71772221, 0.94158805, 0.66323839, 0.21545428, 0.4657406 ],
       [0.2616462 , 0.09129115, 0.67200977, 0.02145852, 0.98943789],
       [0.76029565, 0.45912388, 0.26016576, 0.03410417, 0.07507038]])

In [11]:
np.random.randint(0,3600)

483

In [82]:
np.random.randint(1,10,5)

array([8, 6, 3, 9, 8])

In [13]:
np.random.randint(1,100,20).reshape(5,4)

array([[76, 34, 17, 84],
       [31, 83, 69, 29],
       [ 3, 92, 18, 71],
       [88, 30, 73, 73],
       [72, 60, 62, 48]])

In [5]:
np.random.randint(1,100,(5,4))

array([[60, 45, 63, 71],
       [98, 95,  8, 24],
       [97, 99, 14, 80],
       [92, 25, 22, 96],
       [50,  7, 21, 28]])

# INDEXING

indexing start from 0

In [87]:
arr1[-1]

50

In [88]:
arr2d[2,0]

50

In [89]:
arr2d

array([[10, 20],
       [30, 50],
       [50, 55]])

In [90]:
arr2d[1]

array([30, 50])

# Indexing Revision

In [8]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
arr1[2,1]

7

In [10]:
arr1[2,1] = 17

In [17]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6, 17,  8]])

In [12]:
arr1[2,1]

17

# Slicing

In [13]:
arr1[1:3]

array([[ 3,  4,  5],
       [ 6, 17,  8]])

In [14]:
arr1[1:3,0:2]

array([[ 3,  4],
       [ 6, 17]])

In [21]:
arr1[0:2 ,1:3] 

array([[1, 2],
       [4, 5]])

In [22]:
arr1[0:3:2,0:2]

array([[ 0,  1],
       [ 6, 17]])

In [23]:
arr1[0:3:2,0:3:2]

array([[0, 2],
       [6, 8]])

# 4 Numpy Numerical Operations

In [25]:
list1 = [10,11,12,13,14]
list + 10  #add 10 to each element not possible in list

TypeError: unsupported operand type(s) for +: 'type' and 'int'

In [26]:
arr2 = np.array(list1)
arr2+10

array([20, 21, 22, 23, 24])

In [28]:
arr2*100

array([1000, 1100, 1200, 1300, 1400])

# comparision

In [30]:
# Element wise
a=np.array([1,2,3,4])       
b=np.array([5,2,2,4])
c=np.array([1,2,5,4])

np.array_equal(a,c)           #[True,False,False,True]

False

In [34]:
# Array wise
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,3,2,4])
d=np.array([1,2,3,4])
print(np.array_equal(a,c)," : First Comparision")
print(np.array_equal(a,d))

False  : First Comparision
True


In [36]:
arr3 = np.arange(9).reshape(3,3)
arr4 =np.arange(9).reshape(3,3)

In [37]:
np.equal(arr3,arr4)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
np.array_equal(arr3,arr4)

True

In [40]:
arr3[2,2]=10

In [41]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 10]])

In [42]:
np.equal(arr3,arr4)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True, False]])

In [45]:
loc = np.where(arr3>4)

In [46]:
arr3[loc]

array([ 5,  6,  7, 10])

# Array Mathematics

In [15]:
arr3 = np.arange(9).reshape(3,3)
arr4 =np.arange(9).reshape(3,3)

In [51]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 10]])

In [50]:
arr3[2,2]=10

In [49]:
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arr3+arr4

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 18]])

In [53]:
arr3-arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 2]])

In [55]:
arr3*5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 50]])

In [57]:
arr3*arr4

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 80]])

In [58]:
arr3/arr4

C:\Users\DELL\AppData\Local\Temp\ipykernel_14716\2275417534.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr3/arr4


array([[ nan, 1.  , 1.  ],
       [1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.25]])

In [59]:
np.add(arr3,arr4) # np.subtract,mulple,divede

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 18]])

In [61]:
np.add(arr3,5)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 15]])

In [62]:
np.log(10)

2.302585092994046

In [63]:
np.sin(arr3)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 , -0.54402111]])

In [68]:
np.sin(180)

-0.8011526357338304

In [69]:
arr3[1:2]*10

array([[30, 40, 50]])

# Calculating Min Mean Median

In [70]:
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 10]])

In [71]:
np.mean(arr3)  # For whole date

4.222222222222222

In [72]:
np.min(arr3) # For whole date

0

In [73]:
np.median(arr3) # For whole date

4.0

In [17]:
np.mean(arr3, axis=0)  # axis = 0    0 means column wise in this case

array([3., 4., 5.])

In [75]:
np.median(arr3, axis=0)

array([3., 4., 5.])

In [78]:
a = np.array([1,2,3,4,5,6,7,8])

In [79]:
np.median(a)

4.5

In [82]:
print(np.min(arr3,axis=0))
np.max(arr3, axis=0)

[0 1 2]


array([ 6,  7, 10])

In [83]:




#a

# Array Manipulation

In [84]:
#numpy.concat

In [85]:
np.concatenate((arr3,arr4))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 10],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [94]:
arr5 = np.concatenate((arr3,arr4), axis=1,dtype=('float'))

In [95]:
arr5

array([[ 0.,  1.,  2.,  0.,  1.,  2.],
       [ 3.,  4.,  5.,  3.,  4.,  5.],
       [ 6.,  7., 10.,  6.,  7.,  8.]])

In [91]:
np.hstack((arr3,arr4))

array([[ 0,  1,  2,  0,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7, 10,  6,  7,  8]])

In [96]:
np.vstack((arr3,arr4))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7, 10],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [99]:
arr_1 = np.array([10,20,30])

In [100]:
np.column_stack((arr3,arr_1))

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 20],
       [ 6,  7, 10, 30]])

In [18]:
arr6 =np.arange(42).reshape(7,6)
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [103]:
arr6.shape

(7, 6)

In [106]:
np.hsplit(arr6,2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32],
        [36, 37, 38]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35],
        [39, 40, 41]])]

In [107]:
arr7,arr8 = np.hsplit(arr6,2)

In [109]:
print(arr7)
arr8

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]
 [18 19 20]
 [24 25 26]
 [30 31 32]
 [36 37 38]]


array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35],
       [39, 40, 41]])

In [110]:
np.vsplit(arr6,7)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]]),
 array([[36, 37, 38, 39, 40, 41]])]

# Array Shape Manipulation

In [111]:
arr6.shape

(7, 6)

In [112]:
arr8 = np.arange(15)

In [113]:
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [120]:
arr9 = np.arange(15).reshape(3,5)
arr9

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
arr10 = np.arange(24).reshape(6,1,4)
arr10

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]],

       [[12, 13, 14, 15]],

       [[16, 17, 18, 19]],

       [[20, 21, 22, 23]]])

In [20]:
arr11 = np.arange(25)
arr11

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr12=arr11.reshape(5,5)
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr12.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [138]:
arr12.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [139]:
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [142]:
np.sort(arr6,axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

# Broadcasting

In [143]:
arr21=np.arange(12).reshape(4,3)
arr22=np.arange(9).reshape(3,3)

In [144]:
arr21+arr22

ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [145]:
arr21

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [146]:
arr23 = np.array([10,20,30])

In [147]:
arr21+arr23

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38],
       [19, 30, 41]])

In [150]:
arr24 = arr23.reshape(3,1)
arr24

array([[10],
       [20],
       [30]])

In [151]:
arr23+arr24

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [5]:
import time

In [16]:
def timecal():
    start = time.time()
    print(start)
    a = [i*3 for i in range(100)]
    print(a)
    end =time.time()
    print(end)
    return end-start

In [15]:
timecal()

1666100042.6798058
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291, 294, 297]
1666100042.6798058


0.0

In [17]:
timecal()     #Removed time.sleep(1)

1666100065.2879314
[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99, 102, 105, 108, 111, 114, 117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291, 294, 297]
1666100065.28893


0.0009984970092773438

In [28]:
def timecal1():
    start = time.time()
    current_time=time.localtime()
    print(current_time.tm_year)
    print(current_time)
    print("DATE")
    print(time.strftime("%m/%d/%Y, %H:%M:%S", current_time))
    end =time.time()
    return end-start
timecal1()

2022
time.struct_time(tm_year=2022, tm_mon=10, tm_mday=18, tm_hour=19, tm_min=20, tm_sec=2, tm_wday=1, tm_yday=291, tm_isdst=0)
DATE
10/18/2022, 19:20:02


0.0

In [23]:
def timecal2():
    start = time.time()
    current_time=time.ctime()
    print(current_time)
    end =time.time()
    return end-start
timecal2()

Tue Oct 18 19:17:06 2022


0.0010006427764892578

In [40]:
def decorCalci(fun):
    start = time.time()
    def wrapper(n):
        print("Wrapper Fun")
        fun(n)
        end = time.time()
        return(end-start,'time take for the execution')
    return wrapper

In [41]:
@decorCalci
def lst(n):
    for i in range (n):
        print(i,"main")    

In [43]:
lst(2)

Wrapper Fun
0 main
1 main


(17.9530246257782, 'time take for the execution')

In [152]:

from itertools import permutations

In [167]:
x = list(permutations('xyz'))
print(x)


[('x', 'y', 'z'), ('x', 'z', 'y'), ('y', 'x', 'z'), ('y', 'z', 'x'), ('z', 'x', 'y'), ('z', 'y', 'x')]


In [162]:
total_permutations = [''.join(p) for p in permutations(1235)]
total_permutations

TypeError: 'int' object is not iterable

In [177]:
def permute(data, i, length): 
    print(i,"iteration")
    if i==length: 
        print(''.join(data) )
    else: 
        for j in range(i,length): 
            #swap
            data[i], data[j] = data[j], data[i]
            print(data[j], data[i],'ij')
#             print("123",i,j)
            permute(data, i+1, length)
            data[i], data[j] = data[j], data[i]
#             print('234',j,i)
  

string = "ABC"
n = len(string) 
data = list(string) 
permute(data, 0, n)

0 iteration
A A ij
1 iteration
B B ij
2 iteration
C C ij
3 iteration
ABC
B C ij
2 iteration
B B ij
3 iteration
ACB
A B ij
1 iteration
A A ij
2 iteration
C C ij
3 iteration
BAC
A C ij
2 iteration
A A ij
3 iteration
BCA
A C ij
1 iteration
B B ij
2 iteration
A A ij
3 iteration
CBA
B A ij
2 iteration
B B ij
3 iteration
CAB
